### PR TITLE
verifying the importance of return 0

### PR DESCRIPTION
**Pull request by jfullstackdev**

### CODE REVIEW

**Comment by PerilousApricot** [comment]
Returning an error code is very important, because that's how an external program can know if a sub-program succeeded or failed.

**Comment by jfullstackdev** [comment]
Thank you for the response. 

Is returning 0 the same as returning void? Void methods don't return any value.

Other programmers believe in that, because returning 0 has still a value, because 0 is considered as an integer in C.

I have ideas in my mind, I'm just asking other programmers.

thanks

**Comment by PerilousApricot** [comment]
The details are pretty complex, but long story short, you *must* return an int from `main`. The compiler may help you and do an implicit cast, but you can't depend on that behavior. (void is inherently a "valueless" type - e.g. the void type has no valid byte representations).

**Comment by jfullstackdev** [comment]
that's what I'm actually referring to

bytes representation

but still, programming languages were built depending on the design of the author/s, so we don't see what's happening inside

**Comment by PerilousApricot** [comment]
In C's case, there is a very legalistic definition of how compilers should behave -- otherwise different vendor compilers would be incompatible with each other.

The function signature of `main()` is similarly prescribed - http://c0x.coding-guidelines.com/5.1.2.2.1.html

**Comment by jfullstackdev** [comment]
whoah!

Do you have any idea about the void method of Java?

what is the representation of a void method in binary?

or even just a reference to a binary representation?

thanks

**Comment by PerilousApricot** [comment]
Hi @mongAlvarez - Java and C are *vastly* different languages :) But, the idea is the same -- `void` is a type that has no valid values and, subsequently has no valid byte representation. See e.g. the C99 standard section 6.3.2.2 (http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf)

```
6.3.2.2 void
1 The (nonexistent) value of a void expression (an expression that has type void) shall not
be used in any way, and implicit or explicit conversions (except to void) shall not be
applied to such an expression. If an expression of any other type is evaluated as a void
expression, its value or designator is discarded. (A void expression is evaluated for its
side effects.)
```

Now, you can take a *pointer* to a void variable, but you are not allowed to dereference that pointer and get a value -- there are no valid values of type void.

**Comment by jfullstackdev** [comment]
yes, I know that too, 

but there are just things in my mind, 

like .exe being returned into the original source code

because mainly it will be all about pointing to something which is different for every computer 

thank you @PerilousApricot for your time and ideas

I just want to brainstorm

**Comment by PerilousApricot** [comment]
`pointing to something which is different for every computer`

The nice thing about POSIX and C is that there's a standard for how values are interchanged. You shouldn't need to worry about the actual implementation if you "stay on the reservation"

**Pull request closed without merging**
